# Capítulo 3: Módulos-Parte II
### Paquetes o Librerías

Un paquete puede contener diferentes submódulos, de tal forma que paquetes diferentes pueden contener modulos con nombres similares, pero definiciones diferentes. para evitar que directorios con nombres en común oculten involuntariamente módulos válidos. 

Cuando creamos los paquetes, el archivo `__init__.py`. Este archivo puede estar vacío, sin embargo si queremos inicializar algún paquete o conjunto de varialbes en nuestros submódulos, podemos hacerlo en dicho archivo.

Cuando existen diferentes subpaquetes dentro de un paquete, uno puede importar de forma directa dichos módulos con la sintaxis `nombre_paquete.nombre_subpaquete.nombre_modulo`. De forma similar podemos usar `from nombre_paquete.nombre_subpaquete import nombre_modulo`. Inclusive, si conocemos el nombre de la función que queremos importar podemos usar `form nombre_paquete.nombre_subpaquete.nombre_modulo import nombre_funcion`.

**Nota:** cuando utilizamos la sintaxis `import item.subitem.subsubitem`, el último subsubítem importado debe ser un paquete o módulo, si es una clase, función o variable nos generará un error de tipo importación `ImportError`.

**Nota para los más avanzados:** En el caso que definamos la lista `__all__` en el archivo `__init__.py`, podemos designar que funciones, clases o variables se importan de dicho módulo, para ello usamos la sentencia `__all__ = ['funcion1','clase1','variable1']`.

### Porqué Importar librerías ... ???
Las librerías nos ayudan a utilizar funciones, para facilitarnos el trabajo.

Las librerías que usemos dependen de a que nos dediquemos. Algunas librerías populares son:
1. **pygame**: crear aplicaciones multimedia (videojuegos, imágenes, animaciones, música, etc.)
2. **pillow o pil**: para trabajar con imágenes de forma sencilla.
3. **sqlalchemy**: para los que quieren utilizar bases de datos (en especial con sql).
4. **numpy**: para el álgebra lineal, matrices, transformada de Fourier.
5. **matplotlib**: nos permite crear visualizaciones estáticas, animadas e interactivas en Python.

### Instalación de paquetes usando pip
Para instalar paquetes debemos ejecutar `pip install nombre_paquete` y si queremos desinstalarlo ejecutamos `pip uninstall nombre_paquete`

### Ejemplo 1:
Resolver un sistema lineal.

In [1]:
import numpy as np
# Crear un vector x usando la libreria numpy
x = np.array([1,2,3,4])

In [2]:
x

array([1, 2, 3, 4])

In [4]:
np.array(1)

array(1)

In [5]:
# Crear un vector de unos
N = 50 # Dimension del vector
b = 2*np.ones(N)

In [6]:
print(min(b),max(b),len(b))

2.0 2.0 50


In [7]:
# Crear un vector aleatorio uniforme (0,1) de dimensión N
b = np.random.random(N)

In [8]:
print(min(b),max(b),len(b))

0.05927441066785699 0.9799298372611748 50


In [9]:
# Crear tres vectores aleatorios de vectores aleatorios uniformes (0,1) de dimensión 4. Matriz
C = np.random.random((3,4))

In [10]:
C

array([[0.42499122, 0.58504074, 0.40531408, 0.62704626],
       [0.97926047, 0.63564886, 0.37284911, 0.28344495],
       [0.83109477, 0.22233318, 0.69718653, 0.5302173 ]])

In [11]:
# Producto de una matriz por un vector usando numpy
y = np.dot(C,x)
print(y)

[5.31919998 4.50288534 5.48818991]


In [12]:
# Producto de dos matrices
D = 2*np.ones((4,3))
A = np.dot(C,D)
print(A)

[[4.0847846  4.0847846  4.0847846 ]
 [4.54240679 4.54240679 4.54240679]
 [4.56166356 4.56166356 4.56166356]]


In [13]:
# Producto de dos matrices componente a componente
D = np.ones((3,3))
B = np.multiply(A,D)
print(B)

[[4.0847846  4.0847846  4.0847846 ]
 [4.54240679 4.54240679 4.54240679]
 [4.56166356 4.56166356 4.56166356]]


In [14]:
A * D

array([[4.0847846 , 4.0847846 , 4.0847846 ],
       [4.54240679, 4.54240679, 4.54240679],
       [4.56166356, 4.56166356, 4.56166356]])

In [16]:
np.shape(C)

(3, 4)

In [39]:
from scipy import sparse,linalg
# Matriz sparse de dimension N
A = sparse.diags([1,2,-1],[-2,0,1], shape=(N,N)).toarray()
print(A)

[[ 2. -1.  0. ...  0.  0.  0.]
 [ 0.  2. -1. ...  0.  0.  0.]
 [ 1.  0.  2. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  2. -1.  0.]
 [ 0.  0.  0. ...  0.  2. -1.]
 [ 0.  0.  0. ...  1.  0.  2.]]


In [21]:
# Extraer las dimensiones de una matriz
n,m = np.shape(A)

In [22]:
print('n:',n , '\nm:',m)

n: 50 
m: 50


In [40]:
# Resolver el sistema Ax=b usando el solver por defecto
b = np.ones(n)
x = linalg.solve(A,b)

In [41]:
print(x)

[0.82948354 0.65896708 0.31793416 0.46535187 0.58967082 0.4972758
 0.45990347 0.50947777 0.51623133 0.49236614 0.49421004 0.50465141
 0.50166897 0.49754797 0.49974736 0.50116368 0.49987533 0.49949802
 0.50015972 0.50019476 0.49988755 0.49993481 0.50006439 0.50001632
 0.49996745 0.49999929 0.5000149  0.49999725 0.49999379 0.50000249
 0.50000222 0.49999824 0.49999896 0.50000015 0.49999855 0.49999606
 0.49999227 0.49998308 0.49996222 0.4999167  0.49981648 0.49959519
 0.49910707 0.49803063 0.49565645 0.49041998 0.4788706  0.45339765
 0.39721529 0.27330117]


In [42]:
len(x)

50

In [43]:
min(x)

0.27330117383495145

$$
Ax = b,
\qquad A = LU,
\qquad LU x = b
$$
Tomando $y = Ux$, $Ly = b$

In [44]:
# Resolver el sistema usando factorización LU
P, L, U = linalg.lu(A)
y = linalg.solve(L,b)
x = linalg.solve(U,y)

In [45]:
print(x)

[0.82948354 0.65896708 0.31793416 0.46535187 0.58967082 0.4972758
 0.45990347 0.50947777 0.51623133 0.49236614 0.49421004 0.50465141
 0.50166897 0.49754797 0.49974736 0.50116368 0.49987533 0.49949802
 0.50015972 0.50019476 0.49988755 0.49993481 0.50006439 0.50001632
 0.49996745 0.49999929 0.5000149  0.49999725 0.49999379 0.50000249
 0.50000222 0.49999824 0.49999896 0.50000015 0.49999855 0.49999606
 0.49999227 0.49998308 0.49996222 0.4999167  0.49981648 0.49959519
 0.49910707 0.49803063 0.49565645 0.49041998 0.4788706  0.45339765
 0.39721529 0.27330117]


In [46]:
np.sum(np.dot(A,x) - b)

-1.3322676295501878e-15

**Ejercicio:**
Escribir una función que retorne la matriz identidad usando lazos anidados
$$
\begin{pmatrix}
1 & 0 & 0 & \cdots & 0 \\
0 & 1 & 0 & \cdots & 0 \\
\vdots & \ddots & \ddots & \ddots & \vdots \\
0 & \cdots & 0 & 0 & 1 
\end{pmatrix}
$$

In [23]:
# funcion identidad
def _identidad(N):
    A = np.zeros((N,N))
    for i in range(N):
        for j in range(N):
            if i == j:
                A[i,j] = 1
    return A

In [24]:
_identidad(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Ejercicio:**
Escribir una función para multiplicar matrices componente a componente usando lazos anidados, es decir:
$$
A \times B = \begin{pmatrix}
a_{11} b_{11} & \cdots & a_{1n} b_{1n} \\
\vdots & \ddots & \vdots \\
a_{n1} b_{n1} & \cdots & a_{nn} b_{nn}
\end{pmatrix},
$$
donde
$$
A = \begin{pmatrix}
a_{11} & \cdots & a_{1n} \\
\vdots & \ddots & \vdots \\
a_{n1} & \cdots & a_{nn}
\end{pmatrix}
\qquad \mathrm{y} \qquad
B = \begin{pmatrix}
b_{11} & \cdots & b_{1n} \\
\vdots & \ddots & \vdots \\
b_{n1} & \cdots & b_{nn}
\end{pmatrix}
.
$$

In [26]:
# funcion producto
def producto_punto(A,B):
    n,m = np.shape(A)
    C = np.zeros((n,m))
    for i in range(n):
        for j in range(m):
            C[i,j] = A[i,j] * B[i,j]
    return C

In [29]:
A = 2*np.ones((4,4))
B = 3*np.ones((4,4))
producto_punto(A,B)

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

**Ejercicio:**
Escribir una sola función para:
1. Generar una matriz vacía si no ingresa argumentos.
2. Generar una matriz con elementos aleatorios en el espacio ${[0,1]}^{n\times m}$ si ingresa como argumento las dimensiones $n$ y $m$.
3. Generar una matriz cuadrada con elementos aleatorios en el espacio ${[0,1]}^{n\times n}$ si ingresa como argumento solo el valor $n$.

In [30]:
def m_aleatoria(n=None, m = None):
    if n == None and m == None:
        return []
    elif m == None and n != None:
        return np.random.random((n,n))
    elif m != None and n == None:
        return np.random.random((m,m))
    else:
        return np.random.random((n,m))

## Deber
1. Utilizando el paquete `numpy` genere una función que requiera como argumentos una matriz $A$, un vector $b$ y un entero $n$. Si el vector $b$ ingresado tiene una dimensión menor a $n$, la función deberá agregar ceros al final del vector. Una vez hecho eso, deberá retornar la solución del sistema $Ax =b$ si las dimensiones de la matriz y del vector son adecuadas para el mismo, caso contrario agregará filas o columnas con vectores canónicos a la matriz $A$ de tal forma que sus dimensiones sean adecuadas para resolver el sistema $Ax =b$. 

*Recuerde que para resolver este sistema, la matriz $A$ debería estar en el espacio $\mathbb{R}^{n \times m}$, el vector $x$ en el espacio $\mathbb{R}^{m}$ y el vector $b$ en el espacio $\mathbb{R}^{n}$.*